#!/bin/sh

set -e

installinit_error() {
  status=$?
  # start-stop-daemon doesn't work at the moment. Check we're killing a java
  # app
  pid=$(cat /var/run/dataconnector)
  if $(ps -o comm= $pid | grep -q java); then
    kill $(cat /var/run/dataconnector) && exit 0
  fi
  exit $status
}

if [ -x "/etc/init.d/dataconnector" ]; then
  if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
    invoke-rc.d dataconnector stop || installinit_error
  else
    /etc/init.d/dataconnector stop || installinit_error
  fi
fi
