#!/bin/sh

set -e

PKG_NAME="google-secure-data-connector"
WOODSTOCK_HOME=/etc/opt/$PKG_NAME/woodstock-user"
LOGDIR="/var/log/$PKG_NAME"
RULES_DIR="/var/opt/$PKG_NAME"
USER=daemon

if [ "$1" = "configure" ]; then
  # Set up the user to access the client
  adduser --system --quiet --group --home $WOODSTOCK_HOME --no-create-home \
    woodstock || :

  # Set up the logfile for $PKG_NAME
  if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR
  fi
  chown root:$PKG_NAME $LOGDIR
  chmod 770 $LOGDIR
  for filename in "$PKG_NAME" "apache_access_log" "apache_error_log"; do
    logfile="$LOGDIR/$filename"
    if [ ! -f $logfile ]; then
      touch $logfile
    fi
    chown root:$USER $logfile
    chmod 660 $logfile
  done

  chmod 750 /etc/opt/$PKG_NAME
  chown -R root:$USER /etc/opt/$PKG_NAME
  chown -R root:$USER /opt/$PKG_NAME
  chmod g+w /etc/opt/$PKG_NAME/apache

fi

installinit_error() {
  exit $?
}

# if [ -x "/etc/init.d/$PKG_NAME" ]; then
#  update-rc.d $PKG_NAME defaults 50 15 >/dev/null
#  if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
#    invoke-rc.d $PKG_NAME start || installinit_error
#  else
#    /etc/init.d/$PKG_NAME start || installinit_error
#  fi
#fi
