#!/bin/sh

set -e

OPENSSH_ROOT="/opt/dataconnector/third-party/openssh/"
WOODSTOCK_HOME=${OPENSSH_ROOT}"home/woodstock"
LOGFILE="/var/log/dataconnector"
RULES_DIR="/var/opt/dataconnector"

if [ "$1" = "configure" ]; then
  # Setup the user to run the client
  adduser --system --quiet --group --no-create-home dataconnector || :
  # Set up the user to access the client
  adduser --system --quiet --group --home $WOODSTOCK_HOME --no-create-home \
    woodstock-client || :
    if [ -e ${OPENSSH_ROOT}etc/sshd_config.debian ]; then
      cp ${OPENSSH_ROOT}etc/sshd_config.debian ${OPENSSH_ROOT}etc/sshd_config
    fi
    if [ -e ${OPENSSH_ROOT}bin/start_sshd.sh.debian ]; then
      cp ${OPENSSH_ROOT}bin/start_sshd.sh.debian \
         ${OPENSSH_ROOT}bin/start_sshd.sh
    fi

  # Set up the logfile for dataconnector
  if [ ! -e $LOGFILE ]; then
    touch $LOGFILE
  fi
  chown root:dataconnector $LOGFILE
  chmod 660 $LOGFILE

  if [ ! -d $RULES_DIR ]; then
    mkdir -p $RULES_DIR
    chmod 700 $RULES_DIR
  fi

  if [ ! -f $RULES_DIR/rules ]; then
    touch $RULES_DIR/rules
  fi
  chmod 0600 $RULES_DIR/rules
  chown root:root $RULES_DIR/rules

  chmod 750 /etc/opt/dataconnector
  chown -R root:dataconnector /etc/opt/dataconnector
  chown -R root:dataconnector /opt/dataconnector
fi

installinit_error() {
  exit $?
}

if [ -x "/etc/init.d/dataconnector" ]; then
  update-rc.d dataconnector defaults 50 15 >/dev/null
  if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
    invoke-rc.d dataconnector start || installinit_error
  else
    /etc/init.d/dataconnector start || installinit_error
  fi
fi
